version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: tsig
      POSTGRES_PASSWORD: tsig
      POSTGRES_DB: tsig_2023
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@tsig.com
      PGADMIN_DEFAULT_PASSWORD: tsig
    ports:
      - 5050:80
